GuessIt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('what', include('what_am_i.urls')),
]

app/urls.py
from django.urls import path
from . import views

app_name = 'index'
urlpatterns = [
    path('', views.index, name='index'),
]

what_am_i/urls.py
from django.urls import path
from . import views

app_name = 'what_am_i'
urlpatterns = [
    path('', views.index, name='index'),
]

app/models.py
from django.db import models

# Create your models here.

what_am_i/models.py
from django.db import models

# Create your models here.

class Words(models.Model):
    word = models.CharField(max_length=200)
    joke = models.CharField()

    def __str__(self):
        return self.word

app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'app/index.html')

what_am_i/views.py
from django.shortcuts import render
from .models import Words
from .serializer import WordsSerializer

# Create your views here.

def index(request):
    # Serialize words
    words = Words.objects.all().order_by('?')[:20]
    serializer = WordsSerializer(words, many=True)
    return render(request, 'what_am_i/index.html',
                  {'words': serializer.data}
                  )

app/templates/app/index.html
<html lang="en">
    <head>
        <title>Home</title>
    </head>
    <body>
        <h1>GuessIt</h1>
        <div>

           <a href="{% url 'what_am_i:index' %}">
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row g-0">
                    <div class="col-md-4">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                        <h5 class="card-title">What am I?</h5>
                        <p class="card-text">can you guess what I am?</p>
                        <p class="card-text"><small class="text-muted">highscore: 0</small></p>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
        </a>      
    </body>
    </script>
</html>

what_am_i/templates/what_am_i/index.html
{% extends 'what_am_i/layout.html' %}
{% block body %}
    <h1>What am I?</h1>
    <div id="quiz"></div>
{% endblock %}

what_am_i/templates/what_am_i/layout.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'what_am_i/css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>